name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Before submitting, please check if your issue has already been reported.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug you encountered...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command `ssdl ...`
        2. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      value: |
        - OS: [e.g., macOS 14.1, Ubuntu 22.04, Windows 11]
        - Python version: [e.g., 3.12.1]
        - ssdownload version: [e.g., 0.1.0]
        - Installation method: [pip, uv, conda, etc.]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Relevant error messages or logs
      placeholder: Paste any error messages or relevant logs here...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context about the problem
      placeholder: Add any other context about the problem here...